name = "proxy-worker"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-03-05"
kv_namespaces = [
    { binding = "MY_KV_NAMESPACE", id = "b0e434cca25f4334970208f4c8a5239f" },
]
